build:
  maxIssues: 0

config:
  validation: false

comments:
  active: false

complexity:
  active: false

coroutines:
  active: false

empty-blocks:
  active: false

exceptions:
  active: false

naming:
  active: false

performance:
  active: false

potential-bugs:
  active: false

style:
  active: false

broxy:
  active: true
  UnreferencedDeclaration:
    active: true
    useRepositoryIndex: true
    includePublicDeclarations: true
    includeInternalDeclarations: true
    includeTestSources: false
    ignoreOverriddenDeclarations: true
    allowlistSimpleNames:
      - "main"
    allowlistFqNames: []
    allowlistFqNamePrefixes: []
    excludedPathRegexes:
      - ".*/generated/.*"
